### ISSUE TITLE
'str' object has no attribute 'cpu'

### ISSUE THREAD

**Issue by kartepe4256** [akoksal/BERT-Sentiment-Analysis-Turkish#3]
Merhabalar,
mapping kısmında yakın zamanda bir hata almaya başladım Google colab üzerinde çalışıyorum. Bu hatayı nasıl aşabilirim?
Teşekkürler...

```
AttributeError                            Traceback (most recent call last)
<ipython-input-14-71036244098f> in <module>()
     10     return np.array(X), np.array(y)
     11 
---> 12 X_train, y_train = data_prep(train)
     13 X_val, y_val = data_prep(val)
     14 X_test, y_test = data_prep(test)

1 frames
<ipython-input-12-8e259a97cc89> in feature_extraction(text)
      6     with torch.no_grad():
      7         x, _ = bert(torch.stack([torch.tensor(x)]).to('cuda'))
----> 8         return list(x[0][0].cpu().numpy())

AttributeError: 'str' object has no attribute 'cpu'
```

**Comment by bayramozdennn** [comment]
Bende aynı sorunu yaşıyorum çözebilen var mı?

**Comment by akoksal** [comment]
Merhaba,
Bu transformers kütüphanesinin geriye dönük desteği ile alakalı bir durum. Paylaşılan kod transformers=3.0.2 versiyonu için çalışmakta fakat geçmişe desteği kestikleri için güncel versiyonlarda hata veriyor.

Colab'de veya lokalinizde kütüphaneyi şu şekilde yüklerseniz sorunsuzca çalıştırabilirsiniz:
`pip install transformers==3.0.2`

Eğer transformers'ın güncel 4.0.1 versiyonu ile kodu çalıştırmak isterseniz, feature_extraction kodunu aşağıdaki gibi değiştirmeniz gerekmekte:

```python
def feature_extraction(text):
    x = tokenizer.encode(filter(text))    
    with torch.no_grad():
        y = bert(torch.stack([torch.tensor(x)]).to(device))
    return y.last_hidden_state[0][0].cpu().numpy()
```

Issue'yu kapatıyorum, sorun devam ederse tekrar açabilirsiniz.
