### ISSUE TITLE
BERT features

### ISSUE THREAD

**Issue by yassmine-lam** [akoksal/BERT-Sentiment-Analysis-Turkish#4]
Hi,

for the extrcated BERT features in your notebook, did u extract the last hidden states of the first token [CLS] ?

Thank u

**Comment by akoksal** [comment]
Yes, the feature_extraction function returns the last hidden state of [CLS]. If you want to try it with the latest version of transformers library you have to change feature_extraction code to the below:

```python
def feature_extraction(text):
    x = tokenizer.encode(filter(text))    
    with torch.no_grad():
        y = bert(torch.stack([torch.tensor(x)]).to(device))
    return y.last_hidden_state[0][0].cpu().numpy()
```
